# Generated by Django 2.2.5 on 2019-11-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
