# Generated by Django 2.2.5 on 2019-11-05 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EventApp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=25)),
                ('venue', models.TextField()),
                ('regfee', models.IntegerField()),
                ('tpm', models.IntegerField()),
                ('ddepartment', models.CharField(max_length=200)),
                ('descreption', models.TextField()),
                ('brochure', models.ImageField(upload_to='')),
                ('eventcategory', models.TextField()),
                ('parti', models.IntegerField()),
                ('edate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='departmentn',
            fields=[
                ('did', models.TextField(primary_key=True, serialize=False)),
                ('cdept', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('mname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('regno', models.TextField()),
                ('collegeid', models.TextField()),
                ('departmentid', models.TextField()),
                ('courseid', models.TextField()),
                ('gender', models.CharField(max_length=20)),
                ('profilepic', models.ImageField(blank=True, default='none', upload_to='profiles/')),
                ('contactno', models.IntegerField()),
                ('edate', models.DateField(default=datetime.date(2019, 11, 5), verbose_name=datetime.date)),
                ('yop', models.IntegerField(blank=True, null=True)),
                ('usertype', models.TextField(default='student')),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.CharField(max_length=10)),
                ('wname', models.CharField(max_length=10)),
            ],
        ),
    ]
