# Generated by Django 2.2.5 on 2019-11-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_admin_departmentn_months_user_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='edate',
        ),
        migrations.AlterField(
            model_name='admin',
            name='brochure',
            field=models.ImageField(blank=True, default='none', upload_to='brochures/'),
        ),
    ]
