# Generated by Django 2.2.5 on 2019-11-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0003_auto_20191031_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='addmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.TextField()),
                ('venue', models.TextField()),
                ('date', models.DateField()),
                ('regfee', models.IntegerField()),
                ('tpm', models.IntegerField()),
                ('department', models.TextField()),
                ('descreption', models.TextField()),
                ('brochure', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='collegeid',
            field=models.TextField(default='marian'),
        ),
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AddField(
            model_name='user',
            name='courseid',
            field=models.TextField(default='001mn'),
        ),
        migrations.AddField(
            model_name='user',
            name='departmentid',
            field=models.TextField(default='dept00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(default='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='regno',
            field=models.TextField(default='Regno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='yop',
            field=models.IntegerField(default='000'),
            preserve_default=False,
        ),
    ]
