# Generated by Django 2.2.5 on 2019-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0004_auto_20191102_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmin',
            name='eventid',
            field=models.TextField(default='00a1'),
        ),
    ]
