# Generated by Django 2.2.5 on 2019-11-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0005_addmin_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmin',
            name='eventid',
            field=models.TextField(),
        ),
    ]
