# Generated by Django 2.2.5 on 2019-11-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0006_auto_20191102_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmin',
            name='id',
        ),
        migrations.AlterField(
            model_name='addmin',
            name='eventid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
