# Generated by Django 2.2.5 on 2019-11-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0007_auto_20191102_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmin',
            name='eventname',
            field=models.TextField(default=''),
        ),
    ]
