# Generated by Django 2.2.5 on 2019-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0009_auto_20191103_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('regno', models.TextField()),
                ('collegeid', models.TextField(default='marian')),
                ('departmentid', models.TextField()),
                ('courseid', models.TextField(default='001mn')),
                ('contactno', models.IntegerField(default='0000')),
                ('yop', models.IntegerField()),
            ],
        ),
    ]
