# Generated by Django 2.2.5 on 2019-11-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0010_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collegeid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='courseid',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=25)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventApp.User')),
            ],
        ),
    ]
