# Generated by Django 2.2.5 on 2019-11-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0012_auto_20191103_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2',
            old_name='eventid',
            new_name='username',
        ),
    ]
