# Generated by Django 2.2.5 on 2019-11-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0014_auto_20191103_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('did', models.TextField(primary_key=True, serialize=False)),
                ('cdept', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
