# Generated by Django 2.2.5 on 2019-11-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0015_auto_20191104_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('eventid', models.IntegerField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(default='sss', max_length=25)),
                ('venue', models.TextField(default='sss')),
                ('ddate', models.DateField(default='sss')),
                ('regfee', models.IntegerField(default=123)),
                ('tpm', models.IntegerField(default=127)),
                ('department', models.CharField(default='sss', max_length=200)),
                ('descreption', models.TextField(default='sss')),
            ],
        ),
    ]
