# Generated by Django 2.2.5 on 2019-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0016_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='brochure',
            field=models.ImageField(default='sss', upload_to=''),
        ),
    ]
