# Generated by Django 2.2.5 on 2019-11-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0018_auto_20191104_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='departmentn',
            fields=[
                ('did', models.TextField(primary_key=True, serialize=False)),
                ('cdept', models.CharField(max_length=200)),
            ],
        ),
    ]
