# Generated by Django 2.2.5 on 2019-11-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0019_departmentn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='department',
            new_name='ddepartment',
        ),
    ]
