# Generated by Django 2.2.5 on 2019-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0020_auto_20191104_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='ddate',
        ),
        migrations.AddField(
            model_name='admin',
            name='eventcategory',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='parti',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
