# Generated by Django 2.2.5 on 2019-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0021_auto_20191104_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=10)),
                ('mname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wid', models.CharField(max_length=10)),
                ('wname', models.CharField(max_length=10)),
            ],
        ),
    ]
