# Generated by Django 2.2.5 on 2019-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0022_months_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='none', upload_to='profiles/'),
        ),
    ]
