# Generated by Django 2.2.5 on 2019-11-05 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0023_user_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contactno',
        ),
        migrations.AddField(
            model_name='admin',
            name='edate',
            field=models.DateField(default=datetime.date(2019, 11, 5)),
        ),
        migrations.AddField(
            model_name='user',
            name='edate',
            field=models.DateField(default=datetime.date(2019, 11, 5), verbose_name=datetime.date),
        ),
        migrations.AlterField(
            model_name='user',
            name='yop',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
