# Generated by Django 2.2.5 on 2019-11-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0024_auto_20191105_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
