# Generated by Django 2.2.5 on 2019-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventApp', '0025_delete_user2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
